version: '3.8'

services:
  # PostgreSQL
  postgres:
    image: postgres:15-alpine
    container_name: orderflow-postgres
    environment:
      POSTGRES_DB: orderflow
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./migrations/init.sql:/docker-entrypoint-initdb.d/01-init.sql
      - ./migrations/seed.sql:/docker-entrypoint-initdb.d/02-seed.sql
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres -d orderflow']
      interval: 10s
      timeout: 5s
      retries: 5

  # Temporal Server
  temporal:
    image: temporalio/auto-setup:1.22.3
    container_name: orderflow-temporal
    environment:
      - DB=postgresql
      - DB_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PWD=password
      - POSTGRES_SEEDS=postgres
      - DYNAMIC_CONFIG_FILE_PATH=config/dynamicconfig/development-sql.yaml
    ports:
      - '7233:7233'
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - temporal_data:/var/lib/temporal

  # Temporal Web UI (опционально)
  temporal-web:
    image: temporalio/web:1.15.0
    container_name: orderflow-temporal-web
    environment:
      - TEMPORAL_GRPC_ENDPOINT=temporal:7233
      - TEMPORAL_PERMIT_WRITE_API=true
    ports:
      - '8088:8088'
    depends_on:
      - temporal

volumes:
  postgres_data:
  temporal_data:
